#!/bin/sh
#
# cvstrac:
# Run the cvstrac program against the mysociety repository.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: cvstrac-private,v 1.1 2006-01-26 10:33:06 francis Exp $
#
/data/vhost/cvs.mysociety.org/bin/cvstrac cgi /usr/local/privatecvs/mysociety mysociety-private

