#!/bin/sh
#
# cvstrac-private:
# Run the cvstrac program against the private mySociety repository.
#
# Copyright (c) 2006 UK Citizens Online Democracy. All rights reserved.
# Email: francis@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: cvstrac-private,v 1.4 2006-10-03 07:59:24 francis Exp $
#
/data/vhost/cvs.mysociety.org/bin/cvstrac cgi /usr/local/privatecvs private

