#!/bin/sh
#
# cvstrac:
# Run the cvstrac program against the mysociety repository.
#
# Copyright (c) 2004 UK Citizens Online Democracy. All rights reserved.
# Email: chris@mysociety.org; WWW: http://www.mysociety.org/
#
# $Id: cvstrac,v 1.4 2006-01-26 10:17:51 francis Exp $
#
/data/vhost/cvs.mysociety.org/bin/cvstrac cgi /usr/local/cvs/mysociety mysociety

